/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/model.glb --out src/components/Model3D.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_217ae384-7604-4e30-882f-8ae62879d693'].geometry} material={materials['tripo_material_217ae384-7604-4e30-882f-8ae62879d693']} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/model.glb')
